version: "3"
volumes:
  node_modules:
services:
  sudoku-solid-dev:
    build: .devcontainer
    container_name: sudoku-solid-dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - 8080:3000
